included: # paths to include during linting. `--path` is ignored if present.
  - AEPCampaign/Sources

# A rule that is not enabled by default. Rules conforming to this need to be explicitly enabled by users.
opt_in_rules:
- attributes
- convenience_type
- closure_end_indentation
- closure_spacing
- collection_alignment
- empty_collection_literal
- empty_count
- empty_string
- first_where
- force_unwrapping
- missing_docs
- multiline_arguments
- multiline_function_chains
- multiline_parameters
- number_separator
- operator_usage_whitespace
- pattern_matching_keywords
- redundant_nil_coalescing
- raw_value_for_camel_cased_codable_enum
- redundant_type_annotation
- sorted_imports
- toggle_bool
- trailing_closure
- unneeded_parentheses_in_closure_argument
- switch_case_on_newline
- vertical_parameter_alignment_on_call
- vertical_whitespace_between_cases
disabled_rules: # rule identifiers to exclude from running
  - nesting
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - Package.swift
identifier_name:
    allowed_symbols: "_"
    excluded:
        - id
        - ID
type_name:
    excluded:
        - T
line_length:
    warning: 250
    error: 300
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
file_length:
    warning: 1200
    error: 1500
    ignore_comment_only_lines: true
function_body_length:
    warning: 180
    error: 200
type_body_length:
    warning: 350
    error: 500
analyzer_rules:
  - unused_import
  - unused_declaration
